manifest_endpoints:
  en-US:
    development:
      default: 'https://api.jouleapp.com/manifests/resources.json?includeSlimGuides=true&locale=en-US'
      joule_ready_beta: 'https://d1x6fm6y1dz4pl.cloudfront.net/resources/protein_picker/development/resources.json'
    staging:
      default: 'https://d1azuiz827qxpe.cloudfront.net/resources/v2/staging/en-US/resources.json'
      joule_ready_beta: 'https://d1x6fm6y1dz4pl.cloudfront.net/resources/protein_picker/staging/resources.json'
    production:
      default: 'https://d1azuiz827qxpe.cloudfront.net/resources/v2/production/en-US/resources.json'
      joule_ready_beta: 'https://d1x6fm6y1dz4pl.cloudfront.net/resources/protein_picker/production/resources.json'
  en-GB:
    development:
      default: 'https://api.jouleapp.com/manifests/resources.json?includeSlimGuides=true&locale=en-GB'
      joule_ready_beta: 'https://d1x6fm6y1dz4pl.cloudfront.net/resources/protein_picker/development/resources.json'
    staging:
      default: 'https://d1azuiz827qxpe.cloudfront.net/resources/v2/staging/en-GB/resources.json'
      joule_ready_beta: 'https://d1x6fm6y1dz4pl.cloudfront.net/resources/protein_picker/staging/resources.json'
    production:
      default: 'https://d1azuiz827qxpe.cloudfront.net/resources/v2/production/en-GB/resources.json'
      joule_ready_beta: 'https://d1x6fm6y1dz4pl.cloudfront.net/resources/protein_picker/production/resources.json'
