development: &development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'http://localhost:3000' %>
  front_end_live: false
  back_end_live: true
test: &test
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'http://localhost:3000' %>
  front_end_live: false
  back_end_live: false
staging:
  <<: *development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'http://localhost:3000' %>
  front_end_live: false
  back_end_live: false
production:
  <<: *development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'http://localhost:3000' %>
  front_end_live: false
  back_end_live: false
