development: &development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'http://localhost:3000' %>
  front_end_live: false
  back_end_live: false
test: &test
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'http://localhost:3000' %>
  front_end_live: false
  back_end_live: false
staging:
  <<: *development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'https://spree-staging1.herokuapp.com/' %>
  front_end_live: false
  back_end_live: false
production:
  <<: *development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'https://shop.chefsteps.com/' %>
  front_end_live: false
  back_end_live: false
