development: &development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'https://spree-staging1.herokuapp.com' %>
  api_key: <%= ENV['CS_SPREE_API_KEY'] || 'bac93156686bb720723fb61e66f465a5d61f37d252a5c639' %>
  basic_auth: Basic ZGVsdmU6ZGVlcGVy
  front_end_live: <%= (ENV['CS_IS_SPREE_LIVE'] == 'true') || false %>
test: &test
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'https://spree-staging1.herokuapp.com' %>
  front_end_live: <%= (ENV['CS_IS_SPREE_LIVE'] == 'true') || false %>
staging:
  <<: *development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'https://spree-staging1.herokuapp.com' %>
  api_key: <%= ENV['CS_SPREE_API_KEY'] || 'bac93156686bb720723fb61e66f465a5d61f37d252a5c639' %>
  front_end_live: <%= (ENV['CS_IS_SPREE_LIVE'] == 'true') || false %>
production:
  <<: *development
  hostname: <%= ENV['CS_SPREE_HOSTNAME'] || 'https://shop.chefsteps.com' %>
  api_key: <%= ENV['CS_SPREE_API_KEY'] %>
  front_end_live: <%= (ENV['CS_IS_SPREE_LIVE'] == 'true') || false %>
