#!/bin/bash
set -e

cleanup() {
    echo "Shutting down rails server"
    kill -TERM `cat tmp/pids/angular.pid`
}

trap 'cleanup' SIGINT

if ! type "node" > /dev/null; then
  echo "You need to have Node.js installed"
  echo
  echo "On OSX you can do this by typing"
  echo "$ brew install nodejs"
  echo
  echo "On Ubuntu you can do this by typing"
  echo "$ sudo apt-get install nodejs"
  exit 1
fi

if [ ! -d node_modules ]; then
  echo "You don't have the node modules installed.  Beginning installation:"
  echo
  echo "Installing karma"
  npm install -g karma

  echo "Installing karma-ng-scenario"
  npm install -g karma-ng-scenario

  echo "Installing karma-coffee-preprocessor"
  npm install -g karma-coffee-preprocessor
fi

RAILS_ENV=angular bundle exec rake db:reset
RAILS_ENV=angular bundle exec rake db:test:prepare
RAILS_ENV=angular bundle exec rails runner -e angular "NOT A CHANCE THIS HAS WORKED IN YEARS.
"
bundle exec thin start -p 3001 -e angular -P tmp/pids/angular.pid -d

echo "Waiting for rails server to startup before karma"
sleep 10

echo "Starting up Karma"
karma start spec/angular/karma_e2e_config.js


