require 'csv'
require 'optparse'
require 'date'
require 'pry'
require './shipwire_import'

#
# Takes a CSV from the output of the 'validate_shopify_orders' script and
# sorts it (in FIFO order of placement).
#
# The output of this script is the sorted CSV input.
#
# Options:
#   --input: The input CSV file generated by the 'validate_shopify_export' script.
#   --priority: Optional file of priority order IDs to bump to the top.
#   --blacklist: Optional file of blacklisted order IDs to filter out.
#

# Options parsing
options = {}
option_parser = OptionParser.new do |option|
  option.on('-i', '--input INPUT_FILE', 'CSV export file of validated Shopify orders') do |file|
    options[:input_file] = file
  end

  option.on('-p', '--priority PRIORITY_FILE', 'Optional CSV file of priority orders') do |file|
    options[:priority_file] = file
  end

  option.on('-b', '--blacklist BLACKLIST_FILE', 'Optional CSV file of blacklist orders') do |file|
    options[:blacklist_file] = file
  end
end

option_parser.parse!
raise '--input is required' unless options[:input_file]

order_rows = []
CSV.foreach(options[:input_file], headers: true) do |input_row|
  input_row['processed_at'] = DateTime.parse(input_row['processed_at'])
  order_rows << input_row
end

priority_order_ids = {}
if options[:priority_file]
  priority_index = 1
  CSV.foreach(options[:priority_file], headers: false) do |priority_row|
    order_id = priority_row[0]
    STDERR.puts "Prioritizing order with id #{order_id} with index #{priority_index}"
    priority_order_ids[priority_row[0]] = priority_index
    priority_index += 1
  end
end

blacklist_order_ids = {}
if options[:blacklist_file]
  CSV.foreach(options[:blacklist_file], headers: false) do |blacklist_row|
    blacklist_order_ids[blacklist_row[0]] = true
  end
end

order_rows.sort! do |x, y|
  # Default sort order is by processing timestamp, ascending
  val = x['processed_at'] <=> y['processed_at']

  # Special handling for priority orders
  x_has_priority = !priority_order_ids[x['id']].nil?
  y_has_priority = !priority_order_ids[y['id']].nil?
  if x_has_priority && y_has_priority
    # When comparing two priority orders, the one with the lower index wins
    val = priority_order_ids[x['id']] <=> priority_order_ids[y['id']]
  elsif x_has_priority && !y_has_priority
    val = -1
  elsif !x_has_priority && y_has_priority
    val = 1
  end
  val
end

order_count = 0
output_str = CSV.generate(force_quotes: true) do |output_rows|
  output_rows << ShipwireImport::SHOPIFY_EXPORT_SCHEMA
  order_rows.each do |row|
    if blacklist_order_ids[row['id']]
      STDERR.puts "Order with id #{row['id']} was blacklisted, filterting it out"
    else
      order_count += 1
      output_rows << row
    end
  end
end

puts output_str

STDERR.puts "Sorted #{order_count} orders"
